name: Awesome-CI

on: [push]

jobs:
  awesome-cv-job:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: john821/Awsome-cv@0.0.1
      env:
        GITHUB_TOKEN: ${4cce1a1aa6123b2992779debeabccfc6ea1b256c}
      with:
        FILE_NAME: 'jonathan-boucher.tex'
